### ISSUE TITLE
Why it realised not as View component?

### ISSUE THREAD

**Issue by Insolita** [lubosdz/yii2-template-engine#1]
The idea looks interesting, but it is not allowed to use view files in the usual form.

**Comment by lubosdz** [comment]
Hi, this templating engine is intentionally not bound to any specific component, such as view. That way it has broader usage - within or outside views, inside any component or via 3rd party library - developer will use as suits him. No limiting conventions and less dependencies. I understand that Blade or Twig apply such a scenario (view component), but that's exactly what I did not want to do. 

I am not quite sure what you mean by `it is not allowed to use view files in the usual form`. Pls explain if not answered by previous notes.
