### ISSUE TITLE
Replace a null placeholder with empty string

### ISSUE THREAD

**Issue by ritacionfoli** [lubosdz/yii2-template-engine#2]
Hi there, thank you for this great engine!
I need  to replace a null value of a placeholder with an empty string, 'cause in my db not all of fields could have a value. 
Is there this type of functionality?

Thank you in advance!
Rita

**Comment by lubosdz** [comment]
Perhaps `$engine->setForceReplace("")` may help?
Code [here](https://github.com/lubosdz/yii2-template-engine/blob/main/src/TemplateEngine.php#L153C18-L153C33).
